# Generated by Django 4.0.1 on 2022-01-17 16:30

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='posts/default.jgp', upload_to=posts.models.upload_to_post, verbose_name='Image'),
        ),
    ]
