# Generated by Django 4.0.1 on 2022-01-18 09:06

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='pic',
            field=models.ImageField(default='notifs/default.jpg', upload_to=posts.models.upload_to_notif, verbose_name='Image'),
        ),
    ]
