# Generated by Django 4.0.1 on 2022-01-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_notification_date_notification_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
