# Generated by Django 4.0.1 on 2022-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_notification_post_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
