# Generated by Django 4.0.1 on 2022-01-20 12:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_notification_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pfp',
            field=models.ImageField(default='pfps/default.jgp', upload_to=accounts.models.upload_to_pfp, verbose_name='Image'),
        ),
    ]
