# Generated by Django 4.0.1 on 2022-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_newuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
