# Generated by Django 4.0.1 on 2022-01-21 19:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_newuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='cfp',
            field=models.ImageField(default='cfps/default.png', upload_to=accounts.models.upload_to_cfp, verbose_name='Image'),
        ),
    ]
